alarm_control_panel:
  - platform: manual
    name: Home Alarm
    pending_time: 15
    delay_time: 30
    trigger_time: 10
    disarmed:
      trigger_time: 0

input_boolean:
  alarm_control_panel_disarm:
    name: Alarm Control Panel Disarm
  alarm_control_panel_trigger:
    name: Alarm Control Panel Trigger Test

automation:
  - alias: Alarm Control Panel Trigger All
    trigger:
      - platform: state
        entity_id:
          - input_boolean.alarm_control_panel_trigger
          - binary_sensor.door_sensor_2
        to: "on"
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") != "disarmed" }}
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.home_alarm

  - id: alarm_control_panel_notify
    alias: Alarm Control Panel Send Notification
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "triggered"
    action:
      - service: media_player.play_media
        data:
          entity_id:
            - media_player.bedroom_speaker
            - media_player.living_room_display
          media_content_id: "https://dl.dropboxusercontent.com/s/mpdyuzl5svyuxmq/Rooster%20Crowing-SoundBible.com-43612401.mp3"
          media_content_type: "music"
      - service: notify.notify
        data:
          title: "Alarm"
          message: "Triggered"

  - alias: "Alarm Control Panel Disarm From Trigger"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        from: "triggered"
        to: "disarmed"
    action:
      - service: media_player.media_pause
        data:
          entity_id:
            - media_player.bedroom_speaker
            - media_player.living_room_display


  - id: alarm_control_panel_disarm
    alias: Alarm Control Panel Disarm
    trigger:
      - platform: state
        entity_id: input_boolean.alarm_control_panel_disarm
        to: "on"
      - platform: state
        entity_id:
          - input_boolean.minimote_front_door_8
          - input_boolean.minimote_master_bedroom_8
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") != "disarmed"}}
    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.home_alarm
      - service: notify.ios_ergisch
        data:
          title: "Alarm"
          message: "Disarmed"

  - id: alarm_contry_panel_notify_state
    alias: Alarm Control Panel
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
    action:
      - service: notify.ios_ergisch
        data:
          title: "Test Alarm"
          message: >-
            Home set to {{ states("alarm_control_panel.home_alarm") }}

  ## Set with flic button
  - alias: Alarm Arm Night Flic
    trigger:
      - platform: state
        entity_id: input_boolean.flic_button_1
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") == "disarmed" }}
    action:
      - service: alarm_control_panel.alarm_arm_night
        entity_id: alarm_control_panel.home_alarm
      - service: media_player.media_pause
        entity_id: media_player.bedroom_speaker

  - alias: Alarm Disarm Flic
    trigger:
      - platform: state
        entity_id: input_boolean.flic_button_1
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") != "disarmed" }}
    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.home_alarm
