aarlo:
  username: !secret arloUsername
  password: !secret arloPassword

camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

alarm_control_panel:
  - platform: aarlo
    home_mode_name: mary asleep
    away_mode_name: armed
    night_mode_name: armed

binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    # - ding

sensor:
  - platform: aarlo
    monitored_conditions:
    - last_capture
    - total_cameras
    - battery_level
    - captured_today
    - signal_strength

automation:
  # Keep arlo alarm states in sync with manual alarm panel
  - alias: Aarlo alarm set from main alarm
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") != "pending" or
             states("alarm_control_panel.home_alarm") != "triggered"}}
    action:
      - entity_id: alarm_control_panel.aarlo_lancaster
        service_template: >-
          {% if armed_home %}
          alarm_control_panel.alarm_arm_home
          {% elif  armed_night %}
          alarm_control_panel.alarm_arm_night
          {% elif trigger.to_state.state == "armed_away" %}
          alarm_control_panel.alarm_arm_away
          {% else %}
          alarm_control_panel.alarm_disarm
          {% endif %}
