aarlo:
  username: !secret arloUsername
  password: !secret arloPassword

camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

alarm_control_panel:
  - platform: aarlo
    home_mode_name: Home
    away_mode_name: armed
    night_mode_name: armed

binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    # - ding

sensor:
  - platform: aarlo
    monitored_conditions:
    - last_capture
    - total_cameras
    - battery_level
    - captured_today
    - signal_strength

automation:
  # Keep arlo alarm states in sync with manual alarm panel
  - alias: Aarlo alarm set from main alarm
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") != "pending" or
             states("alarm_control_panel.home_alarm") != "triggered"}}
    action:
      - entity_id: alarm_control_panel.aarlo_lancaster
        service_template: >-
          {% if trigger.to_state.state == "armed_home" %}
          alarm_control_panel.alarm_arm_home
          {% elif trigger.to_state.state == "armed_night" %}
          alarm_control_panel.alarm_arm_night
          {% elif trigger.to_state.state == "armed_away" %}
          alarm_control_panel.alarm_arm_away
          {% elif trigger.to_state.state == "disarmed" and
             states.input_select.mary_status == "Asleep" %}
          alarm_control_panel.alarm_arm_home
          {% else %}
          alarm_control_panel.alarm_disarm
          {% endif %}

  - alias: Aarlo to home when Mary asleep
    trigger:
      - platform: state
        entity_id: input_select.mary_status
        to: "Asleep"
    action:
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.aarlo_lancaster

  - alias: Aarlo to disarm when Mary awake
    trigger:
      - platform: state
        entity_id: input_select.mary_status
        to: "Home"
    condition:
      - condition: template
        value_template: >-
          {{ states('alarm_control_panel.home_alarm') == 'disarmed' }}
    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.aarlo_lancaster
