input_select:
  angela_status:
    name: "Angela's Status"
    options:
      - Home
      - Away
      - Asleep

automation:
  - alias: "Angela Home Away"
    trigger:
      - platform: state
        entity_id: input_boolean.minimote_front_door_3
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.angela_status
          option: >-
            {% if states("input_select.angela_status") != "Away" %}
            Away
            {% else %}
            Home
            {% endif %}

  - alias: "Angela Home Asleep"
    trigger:
      - platform: state
        entity_id: input_boolean.minimote_master_bedroom_3
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.angela_status
          option: >-
            {% if states("input_select.angela_status") != "Asleep" %}
            Asleep
            {% else %}
            Home
            {% endif %}

  - alias: "Angela Alarm Status Asleep"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: 'armed_night'
    condition:
      - condition: template
        value_template: >-
          {{ states("input_select.angela_status") == "Home" }}
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.angela_status
          option: 'Asleep'
