sensor:
  platform: template
  sensors:
    aeotec_dsb05_multisensor_battery_2:
      friendly_name: Aeotec DSB05 Multisensor Battery
      unit_of_measurement: '%'
      value_template: >-
        {{ state_attr("zwave.aeotec_dsb05_multisensor_2", "battery_level") }}
    aeotec_zw100_multisensor_6_battery_3:
      friendly_name: Aeotec ZW100 Multisensor 6 Battery
      value_template: >-
        {{ state_attr("zwave.aeotec_zw100_multisensor_6_3", "battery_level") }}
      unit_of_measurement: '%'
    linear_wadwaz_1_door_window_sensor_battery:
      friendly_name: Linear WADWAZ-1 Door Window Sensor Battery 1
      value_template: >-
        {{ state_attr("zwave.linear_wadwaz_1_door_window_sensor", "battery_level") }}
      unit_of_measurement: '%'
    linear_wadwaz_1_door_window_sensor_battery_2:
      friendly_name: Linear WADWAZ-1 Door Window Sensor Battery 2
      value_template: >-
        {{ state_attr("zwave.linear_wadwaz_1_door_window_sensor_2", "battery_level") }}
      unit_of_measurement: '%'
    linear_wadwaz_1_door_window_sensor_battery_3:
      friendly_name: Linear WADWAZ-1 Door Window Sensor Battery 3
      value_template: >-
        {{ state_attr("zwave.linear_wadwaz_1_door_window_sensor_3", "battery_level") }}
      unit_of_measurement: '%'
    linear_wadwaz_1_door_window_sensor_battery_4:
      friendly_name: Linear WADWAZ-1 Door Window Sensor Battery 4
      value_template: >-
        {{ state_attr("zwave.linear_wadwaz_1_door_window_sensor_4", "battery_level") }}
      unit_of_measurement: '%'
    linear_wapirz_1_motion_sensor_battery:
      friendly_name: Linear WAPIRZ-1 Motion Sensor Battery 1
      value_template: >-
        {{ state_attr("zwave.linear_wapirz_1_motion_sensor", "battery_level") }}
      unit_of_measurement: '%'
    linear_wapirz_1_motion_sensor_battery_2:
      friendly_name: Linear WAPIRZ-1 Motion Sensor Battery 2
      value_template: >-
        {{ state_attr("zwave.linear_wapirz_1_motion_sensor_2", "battery_level") }}
      unit_of_measurement: '%'
    linear_wapirz_1_motion_sensor_battery_3:
      friendly_name: Linear WAPIRZ-1 Motion Sensor Battery 3
      value_template: >-
        {{ state_attr("zwave.linear_wapirz_1_motion_sensor_3", "battery_level") }}
      unit_of_measurement: '%'
